import { generateCorrelationYAML, generateCorrelationConfig } from '../data/correlationDefaults';

interface CICDPipelineProps {
  activities: string[];
  splBlocks: Array<{ title: string; env: 'aws' | 'onprem'; spl: string }>;
}

export function CICDPipeline({ activities, splBlocks }: CICDPipelineProps) {
  const workflowYaml = generateWorkflowYaml(activities, splBlocks);

  const handleDownload = () => {
    const blob = new Blob([workflowYaml], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'detection-ci.yml';
    a.click();
    URL.revokeObjectURL(url);
  };

  const handleCopy = async () => {
    await navigator.clipboard.writeText(workflowYaml);
  };

  return (
    <div className="log-rec-section" style={{ marginTop: '20px' }}>
      <div className="log-rec-hd">🔄 CI/CD Pipeline — Detection as Code</div>
      <div style={{ padding: '12px 16px' }}>
        <div style={{ fontFamily: 'var(--mono)', fontSize: '9px', color: 'var(--text-dim)', lineHeight: 1.6, marginBottom: '12px' }}>
          GitHub Actions workflow for linting, validating, and deploying detections to Splunk ES.
          Place in <code style={{ color: 'var(--green)' }}>.github/workflows/detection-ci.yml</code>
        </div>
        <div style={{ display: 'flex', gap: '8px', marginBottom: '12px' }}>
          <button className="copy-btn" onClick={handleCopy}>Copy Workflow</button>
          <button className="copy-btn" onClick={handleDownload}>Download .yml</button>
        </div>
        <pre style={{
          fontFamily: 'var(--mono)', fontSize: '9px', color: '#86efac', lineHeight: 1.6,
          background: 'var(--bg)', border: '1px solid var(--border)', padding: '14px',
          maxHeight: '500px', overflowY: 'auto', whiteSpace: 'pre-wrap',
        }}>
          {workflowYaml}
        </pre>
      </div>
    </div>
  );
}

function generateWorkflowYaml(activities: string[], splBlocks: Array<{ title: string; env: 'aws' | 'onprem'; spl: string }>): string {
  const detectionDirs = splBlocks.map(b => `detections/${b.env}/${b.title.toLowerCase().replace(/[^a-z0-9]+/g, '_')}`).join('\n          ');

  return `# Detection-as-Code CI/CD Pipeline
# Generated by WaldoHunt 2.0
# Deploys ${splBlocks.length} insider threat detections to Splunk ES

name: Detection CI/CD

on:
  push:
    paths:
      - 'detections/**'
  pull_request:
    paths:
      - 'detections/**'
  workflow_dispatch:

jobs:
  lint:
    name: Lint SPL
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: SPL Syntax Check
        run: |
          for file in \$(find detections -name '*.spl'); do
            echo "Linting: \$file"
            python3 .github/scripts/spl_lint.py "\$file"
          done

  validate:
    name: Validate Detection Schema
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4
      - name: Validate YAML Schema
        run: |
          for file in \$(find detections -name 'correlation.yaml'); do
            echo "Validating: \$file"
            python3 .github/scripts/validate_detection.py "\$file"
          done

  deploy-dev:
    name: Deploy to Dev
    runs-on: ubuntu-latest
    needs: validate
    environment: dev
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to Splunk ES (Dev)
        env:
          SPLUNK_HOST: \${{ secrets.SPLUNK_DEV_HOST }}
          SPLUNK_TOKEN: \${{ secrets.SPLUNK_DEV_TOKEN }}
        run: |
          python3 .github/scripts/deploy_detections.py \\
            --splunk-host "\$SPLUNK_HOST" \\
            --splunk-token "\$SPLUNK_TOKEN" \\
            --detection-dir detections/ \\
            --mode report

  test:
    name: Run Detection Tests
    runs-on: ubuntu-latest
    needs: deploy-dev
    steps:
      - uses: actions/checkout@v4
      - name: Wait for baseline
        run: sleep 300  # 5 min for ES to process
      - name: Verify detection runs
        env:
          SPLUNK_HOST: \${{ secrets.SPLUNK_DEV_HOST }}
          SPLUNK_TOKEN: \${{ secrets.SPLUNK_DEV_TOKEN }}
        run: |
          python3 .github/scripts/test_detections.py \\
            --splunk-host "\$SPLUNK_HOST" \\
            --splunk-token "\$SPLUNK_TOKEN" \\
            --detection-dirs \\
${detectionDirs}

  deploy-prod:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: test
    environment: production
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to Splunk ES (Prod)
        env:
          SPLUNK_HOST: \${{ secrets.SPLUNK_PROD_HOST }}
          SPLUNK_TOKEN: \${{ secrets.SPLUNK_PROD_TOKEN }}
        run: |
          python3 .github/scripts/deploy_detections.py \\
            --splunk-host "\$SPLUNK_HOST" \\
            --splunk-token "\$SPLUNK_TOKEN" \\
            --detection-dir detections/ \\
            --mode alert

  notify:
    name: Notify
    runs-on: ubuntu-latest
    needs: deploy-prod
    if: always()
    steps:
      - name: Slack Notification
        uses: slackapi/slack-github-action@v2
        with:
          payload: |
            {
              "text": "Detection deployment \${{ job.status }}: \${splBlocks.length} detections deployed to Splunk ES Prod by \${{ github.actor }}"
            }
`;
}
