import { useState } from 'react';
import { generateSigma } from '../data/sigmaTemplates';
import { generateKQL } from '../data/kqlTemplates';
import { generateCorrelationConfig, generateCorrelationYAML } from '../data/correlationDefaults';
import { MITRE_MAP } from '../data/mitreMap';
import { ACTIVITIES } from '../data/activities';

interface ExportPanelProps {
  activities: string[];
  pattern: string | null;
  env: 'aws' | 'onprem' | 'both';
  splBlocks: Array<{ title: string; env: 'aws' | 'onprem'; spl: string }>;
}

type ExportFormat = 'spl' | 'sigma' | 'kql' | 'navigator' | 'correlation_yaml' | 'dac_bundle';

export function ExportPanel({ activities, pattern, env, splBlocks }: ExportPanelProps) {
  const [activeFormat, setActiveFormat] = useState<ExportFormat>('spl');
  const [copied, setCopied] = useState(false);

  const actLabels: Record<string, string> = {};
  (ACTIVITIES[pattern || ''] || []).forEach((a) => { actLabels[a.val] = a.title; });

  const generateExport = (format: ExportFormat): string => {
    switch (format) {
      case 'spl': {
        return splBlocks.map((b) =>
          `# ${b.env.toUpperCase()} — ${b.title}\n# MITRE: ${(MITRE_MAP[activities[0]] || []).map(t => t.tid).join(', ')}\n${b.spl}\n`
        ).join('\n');
      }

      case 'sigma': {
        return activities.map((act) => {
          const envs: ('aws' | 'onprem')[] = env === 'both' ? ['aws', 'onprem'] : [env];
          return envs.map((e) => {
            const rule = generateSigma(act, actLabels[act] || act, e);
            if (!rule) return null;
            return `# Sigma Rule: ${rule.title}\n${JSON.stringify(rule, null, 2)}`;
          }).filter(Boolean).join('\n\n');
        }).filter(Boolean).join('\n\n---\n\n');
      }

      case 'kql': {
        return activities.map((act) => {
          const envs: ('aws' | 'onprem')[] = env === 'both' ? ['aws', 'onprem'] : [env as 'aws' | 'onprem'];
          return envs.map((e) => {
            const kql = generateKQL(act, actLabels[act] || act, e);
            if (!kql) return null;
            return `// KQL: ${kql.title}\n// Required Tables: ${kql.requiredTables.join(', ')}\n// MITRE Tactics: ${kql.mitreTactics.join(', ')}\n\n${kql.query}`;
          }).filter(Boolean).join('\n\n');
        }).filter(Boolean).join('\n\n---\n\n');
      }

      case 'navigator': {
        // Generate ATT&CK Navigator layer JSON
        const allTtps = new Set<string>();
        activities.forEach((act) => {
          (MITRE_MAP[act] || []).forEach((t) => allTtps.add(t.tid));
        });
        const layer = {
          name: `WaldoHunt — ${pattern || 'Detection'} Coverage`,
          description: `Insider threat detection coverage for CERT/CC pattern: ${pattern}. Generated by WaldoHunt 2.0.`,
          domain: 'mitre-enterprise',
          versions: { attack: '15', navigator: '4.9', layer: '4.5' },
          techniques: Array.from(allTtps).map((tid) => ({
            techniqueID: tid,
            score: 100,
            color: '#22c55e',
            comment: '',
            enabled: true,
          })),
        };
        return JSON.stringify(layer, null, 2);
      }

      case 'correlation_yaml': {
        return splBlocks.map((b) => {
          const act = activities[0];
          const config = generateCorrelationConfig(act, b.title, b.spl, b.env);
          return generateCorrelationYAML(config);
        }).join('---\n\n');
      }

      case 'dac_bundle': {
        // Detection as Code bundle — directory structure manifest
        return splBlocks.map((b) => {
          const act = activities[0];
          const config = generateCorrelationConfig(act, b.title, b.spl, b.env);
          return [
            `# Detection as Code Bundle: ${b.title}`,
            `# Path: detections/${b.env}/${act}/`,
            '',
            '├── correlation.yaml       # Splunk ES correlation search config',
            '├── detection.spl          # Raw SPL search',
            '├── sigma.yaml             # Sigma rule (if applicable)',
            '├── kql.txt                # Microsoft KQL (if applicable)',
            '└── README.md              # Detection documentation',
            '',
            '--- correlation.yaml ---',
            generateCorrelationYAML(config),
            '--- detection.spl ---',
            b.spl,
          ].join('\n');
        }).join('\n\n' + '='.repeat(72) + '\n\n');
      }

      default:
        return '';
    }
  };

  const handleCopy = async () => {
    await navigator.clipboard.writeText(generateExport(activeFormat));
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    const content = generateExport(activeFormat);
    const extensions: Record<string, string> = {
      spl: 'spl',
      sigma: 'json',
      kql: 'kql',
      navigator: 'json',
      correlation_yaml: 'yaml',
      dac_bundle: 'txt',
    };
    const ext = extensions[activeFormat] || 'txt';
    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `waldohunt-${pattern || 'detection'}-${activeFormat}.${ext}`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const formats: { val: ExportFormat; label: string; desc: string }[] = [
    { val: 'spl', label: 'SPL', desc: 'Raw Splunk Processing Language' },
    { val: 'sigma', label: 'Sigma', desc: 'Vendor-agnostic YAML rules' },
    { val: 'kql', label: 'KQL', desc: 'Microsoft Sentinel / Defender' },
    { val: 'navigator', label: 'ATT&CK Navigator', desc: 'MITRE Navigator layer JSON' },
    { val: 'correlation_yaml', label: 'ES Config', desc: 'Splunk ES correlation YAML' },
    { val: 'dac_bundle', label: 'DaC Bundle', desc: 'Detection-as-Code package' },
  ];

  const exportContent = generateExport(activeFormat);
  const lineCount = exportContent.split('\n').length;

  return (
    <div className="mitre-section" style={{ marginTop: '32px' }}>
      <div className="mitre-hd">
        <div className="mitre-hd-title">📦 Export Detection Package</div>
        <div className="mitre-hd-sub">
          {lineCount} lines · {splBlocks.length} detection blocks
        </div>
      </div>
      <div style={{ padding: '12px 16px', display: 'flex', flexWrap: 'wrap', gap: '6px', borderBottom: '1px solid var(--border)' }}>
        {formats.map((f) => (
          <button
            key={f.val}
            className={`log-toggle ${activeFormat === f.val ? 'selected' : ''}`}
            onClick={() => { setActiveFormat(f.val); setCopied(false); }}
            title={f.desc}
          >
            <span className="dot" />
            {f.label}
          </button>
        ))}
        <div style={{ flex: 1 }} />
        <button className="copy-btn" onClick={handleCopy} style={{ marginRight: '6px' }}>
          {copied ? 'Copied!' : 'Copy'}
        </button>
        <button className="copy-btn" onClick={handleDownload}>Download</button>
      </div>
      <pre className="spl" style={{ maxHeight: '500px', overflowY: 'auto', margin: 0, border: 'none' }}>
        {exportContent}
      </pre>
    </div>
  );
}
