import { ACTIVITIES } from '../data/activities';
import { MITRE_MAP } from '../data/mitreMap';
import { PLAYBOOKS } from '../data/playbooks';
import { FP_GUIDANCE } from '../data/fpGuidance';
import { BASELINE_GUIDANCE } from '../data/baselineWindows';
import { COMPLIANCE_MAP } from '../data/complianceMapping';
import { generateRBAConfig } from '../data/rbaConfig';
import type { Pattern } from '../types';

interface MarkdownBriefProps {
  activity: string;
  pattern: Pattern | null;
  env: 'aws' | 'onprem' | 'both';
}

export function MarkdownBrief({ activity, pattern, env }: MarkdownBriefProps) {
  const actLabels: Record<string, string> = {};
  (ACTIVITIES[pattern || ''] || []).forEach(a => { actLabels[a.val] = a.title; });

  const title = actLabels[activity] || activity.replace(/_/g, ' ');
  const mitre = MITRE_MAP[activity] || [];
  const playbook = PLAYBOOKS[activity];
  const fp = FP_GUIDANCE[activity];
  const baseline = BASELINE_GUIDANCE[activity];
  const compMap = COMPLIANCE_MAP[activity] || COMPLIANCE_MAP.delete_data;
  const rba = generateRBAConfig(activity);

  const markdown = `# Detection Brief: ${title}

**WaldoHunt 2.0** | ${new Date().toISOString().split('T')[0]}
Environment: ${env.toUpperCase()} | CERT Pattern: ${pattern || 'N/A'}

---

## Overview

This detection identifies **${title.toLowerCase()}** activity in ${env === 'aws' ? 'AWS cloud' : 'on-prem/hybrid'} environments. ${fp ? `Expected noise level: **${fp.noiseLevel.toUpperCase()}**. ${fp.expectedBaseline}` : ''}

## MITRE ATT&CK Mapping

| Technique ID | Tactic | Technique |
|---|---|---|
${mitre.map(t => `| [${t.tid}](${t.url}) | ${t.tactic} | ${t.technique} |`).join('\n')}

## Detection Logic

The search ${activity === 'priv_escalation' ? 'identifies' : 'detects'} ${title.toLowerCase()} by:
${getDetectionLogicSummary(activity)}

## Expected Baseline

${baseline ? `- **Recommended baseline window:** ${baseline.recommendedDays} days (${baseline.minimumDays} minimum)
- **Statistical method:** ${baseline.statisticalMethod}
- **Threshold:** ${baseline.thresholdGuidance}
- **Data volume:** ${baseline.dataVolumeEstimate}` : '- Run in report mode for 14 days to establish baseline'}

## False Positive Guidance

${fp ? fp.commonScenarios.map((s, i) => `${i + 1}. ${s}`).join('\n') : 'No specific FP guidance available.'}

### Tuning Tips
${fp ? fp.tuningTips.map(s => `- ${s}`).join('\n') : '- Use baseline data to calibrate thresholds'}

## Response Playbook

${playbook ? `- **SLA:** ${playbook.sla}
- **Contact:** ${playbook.contactRole}
- **Immediate Actions:**
${playbook.immediateActions.map((a, i) => `  ${i + 1}. ${a}`).join('\n')}
- **Escalation Criteria:** ${playbook.escalationCriteria}` : '- Follow standard SOC incident response procedures'}

## Compliance Mapping

### NIST 800-53
${compMap.nist80053.map(n => `- **${n.id}** — ${n.title} (${n.family})`).join('\n')}

### CIS Controls v8
${compMap.cis8.map(c => `- **${c.id}** — ${c.title} [${c.ig}]`).join('\n')}

## Risk-Based Alerting

- **Risk Score:** ${rba.riskScore}
- **Object:** ${rba.riskObject} → \`${rba.riskObjectField}\`
- **Urgency/Priority:** ${rba.urgency} / ${rba.priority}
- **Decay:** ${rba.decayFunction} ${rba.decayWindow}
- **Actions:** ${rba.alertAction}

## Deployment Readiness

- [ ] SPL validated against Splunk index
- [ ] Thresholds calibrated against baseline
- [ ] False positives reviewed and classified
- [ ] Playbook reviewed by SOC team
- [ ] Risk scoring configured in ES
- [ ] Peer review completed by second analyst

---

*Generated by WaldoHunt 2.0 — Practitioner-Built Detection Engineering*
`;

  const handleCopy = () => navigator.clipboard.writeText(markdown);
  const handleDownload = () => {
    const blob = new Blob([markdown], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `detection-brief-${activity}.md`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="log-rec-section" style={{ marginTop: '20px' }}>
      <div className="log-rec-hd">📝 Markdown Detection Brief</div>
      <div style={{ padding: '12px 16px' }}>
        <div style={{ fontFamily: 'var(--mono)', fontSize: '9px', color: 'var(--text-dim)', lineHeight: 1.6, marginBottom: '12px' }}>
          One-page detection summary for leadership review, peer review, or audit documentation.
        </div>
        <div style={{ display: 'flex', gap: '8px', marginBottom: '12px' }}>
          <button className="copy-btn" onClick={handleCopy}>Copy Markdown</button>
          <button className="copy-btn" onClick={handleDownload}>Download .md</button>
        </div>
        <pre style={{
          fontFamily: 'var(--mono)', fontSize: '9px', color: '#86efac',
          background: 'var(--bg)', padding: '14px', border: '1px solid var(--border)',
          lineHeight: 1.5, whiteSpace: 'pre-wrap', maxHeight: '600px', overflowY: 'auto',
        }}>
          {markdown}
        </pre>
      </div>
    </div>
  );
}

function getDetectionLogicSummary(activity: string): string {
  const summaries: Record<string, string> = {
    delete_data: '- Counting bulk DeleteObject/DeleteBucket API calls exceeding 100 in 24 hours\n- Grouping by IAM user ARN and AWS region\n- Evaluating risk based on delete volume and bucket count',
    s3_exfil: '- Counting GetObject operations exceeding 200 downloads or 1 GB in 24 hours\n- Grouping by requester identity\n- Correlating download volume with sensitivity classification',
    priv_escalation: '- Detecting AttachUserPolicy with AdministratorAccess\n- Counting privilege-related API calls exceeding 2 in 24 hours\n- Identifying admin grants and multi-action escalation patterns',
    lateral_move: '- Detecting AssumeRole chains across multiple accounts\n- Counting cross-account role assumptions exceeding 2 unique accounts\n- Tracking role chaining depth and first-time cross-account access',
    credential_harvest: '- Detecting GetSecretValue and GetSessionToken calls exceeding 10 in 24 hours\n- Identifying access to previously-unaccessed secrets\n- Correlating with unusual IPs or off-hours access',
    recon: '- Counting Describe/List API calls exceeding 50 in 24 hours with 5+ unique APIs\n- Tracking services probed across EC2, IAM, S3, Lambda\n- Identifying first-time service exploration patterns',
    c2_comms: '- Analyzing VPC Flow Logs for connections to 50+ unique external destinations\n- Detecting beaconing patterns (regular-interval connections)\n- Measuring port diversity and byte volume',
    persistence: '- Detecting IAM user/role creation, access key generation, and scheduled task creation\n- Counting persistence mechanisms exceeding 2 types in 24 hours\n- Identifying backdoor trust policies allowing external accounts',
  };
  return summaries[activity] || `- Analyzing ${activity.replace(/_/g, ' ')} patterns in log data\n- Grouping by user identity and source IP\n- Applying statistical thresholds for anomaly detection`;
}
