import { useState } from 'react';
import { generateYARAL } from '../data/yaraLTemplates';
import { generateEQL } from '../data/eqlTemplates';
import { generateDatadog } from '../data/datadogTemplates';
import { ACTIVITIES } from '../data/activities';
import type { Pattern } from '../types';

interface MultiPlatformExportProps {
  activities: string[];
  patterns: Pattern[];
  env: 'aws' | 'onprem' | 'both';
}

type Platform = 'chronicle' | 'elastic' | 'datadog';

export function MultiPlatformExport({ activities, patterns, env }: MultiPlatformExportProps) {
  const [platform, setPlatform] = useState<Platform>('chronicle');
  const [copied, setCopied] = useState(false);

  const actLabels: Record<string, string> = {};
  patterns.forEach(p => (ACTIVITIES[p || ''] || []).forEach(a => { actLabels[a.val] = a.title; }));

  const envs: ('aws' | 'onprem')[] = env === 'both' ? ['aws', 'onprem'] : [env as 'aws' | 'onprem'];

  const generate = (): string => {
    switch (platform) {
      case 'chronicle': {
        return activities.flatMap(act =>
          envs.map(e => {
            const rule = generateYARAL(act, actLabels[act] || act, e);
            if (!rule) return null;
            return `# YARA-L 2.0 Rule: ${rule.name}
# Environment: ${e.toUpperCase()}
# https://cloud.google.com/chronicle/docs/detection/yara-l-2-0-overview

rule ${sanitizeRuleName(rule.name)} {
  meta:
    author = "WaldoHunt 2.0"
    description = "${rule.description}"
    severity = "High"
    mitre_attack = ["T1485", "T1490"]

  events:
    ${rule.events}

  match:
    ${rule.match}

  outcome:
    ${rule.outcome}

  condition:
    $delete_count > 0
}`;
          }).filter(Boolean).join('\n\n')
        ).filter(Boolean).join('\n\n---\n\n');
      }

      case 'elastic': {
        return activities.flatMap(act =>
          envs.map(e => {
            const rule = generateEQL(act, actLabels[act] || act, e);
            if (!rule) return null;
            return `# Elastic Security Detection Rule
# Generated by WaldoHunt 2.0

name: "${rule.name}"
description: "${rule.description}"
risk_score: ${rule.riskScore}
severity: "${rule.severity}"
type: "eql"
language: "${rule.language}"
query: |
  ${rule.query.split('\n').join('\n  ')}
tags:
${rule.tags.map(t => `  - "${t}"`).join('\n')}`;
          }).filter(Boolean).join('\n\n')
        ).filter(Boolean).join('\n\n---\n\n');
      }

      case 'datadog': {
        return activities.flatMap(act =>
          envs.map(e => {
            const rule = generateDatadog(act, actLabels[act] || act, e);
            if (!rule) return null;
            return JSON.stringify(rule, null, 2);
          }).filter(Boolean).join('\n\n')
        ).filter(Boolean).join('\n\n---\n\n');
      }

      default: return '';
    }
  };

  const handleCopy = async () => {
    await navigator.clipboard.writeText(generate());
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const extensions: Record<Platform, string> = { chronicle: 'yaral', elastic: 'ndjson', datadog: 'json' };

  const handleDownload = () => {
    const content = generate();
    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `waldohunt-${platform}-detections.${extensions[platform]}`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const platforms: { val: Platform; label: string; vendor: string; icon: string }[] = [
    { val: 'chronicle', label: 'YARA-L 2.0', vendor: 'Google SecOps (Chronicle)', icon: '🔵' },
    { val: 'elastic', label: 'EQL', vendor: 'Elastic Security', icon: '🟡' },
    { val: 'datadog', label: 'JSON Rules', vendor: 'Datadog Cloud SIEM', icon: '🟣' },
  ];

  const content = generate();
  const lineCount = content.split('\n').length;

  return (
    <div className="mitre-section" style={{ marginTop: '32px' }}>
      <div className="mitre-hd">
        <div className="mitre-hd-title">🌐 Multi-Platform Export</div>
        <div className="mitre-hd-sub">{lineCount} lines · {activities.length} detections · {envs.length} environments</div>
      </div>

      <div style={{ padding: '12px 16px', display: 'flex', flexWrap: 'wrap', gap: '6px', borderBottom: '1px solid var(--border)' }}>
        {platforms.map(p => (
          <button key={p.val}
            className={`log-toggle ${platform === p.val ? 'selected' : ''}`}
            onClick={() => { setPlatform(p.val); setCopied(false); }}>
            <span className="dot" />{p.icon} {p.label}
            <span style={{ fontSize: '8px', color: 'var(--text-dim)', marginLeft: '4px' }}>({p.vendor})</span>
          </button>
        ))}
        <div style={{ flex: 1 }} />
        <button className="copy-btn" onClick={handleCopy}>{copied ? 'Copied!' : 'Copy'}</button>
        <button className="copy-btn" onClick={handleDownload} style={{ marginLeft: '6px' }}>Download</button>
      </div>

      <pre style={{
        fontFamily: 'var(--mono)', fontSize: '10px', color: '#86efac',
        background: 'var(--bg)', padding: '14px', border: 'none',
        lineHeight: 1.6, whiteSpace: 'pre-wrap', maxHeight: '500px', overflowY: 'auto',
      }}>
        {content}
      </pre>
    </div>
  );
}

function sanitizeRuleName(name: string): string {
  return name.replace(/[^a-zA-Z0-9_\s-]/g, '').replace(/\s+/g, '_');
}
