// Splunk Data Model Acceleration Guide
// Per data model: recommended acceleration period, summary range, cron schedules

export interface AccelerationConfig {
  dataModel: string;
  dataset: string;
  accelerationPeriod: string;
  summaryRange: string;
  cronSchedule: string;
  estimatedDiskGB: string;
  keyFields: string[];
  dependenciesNote: string;
}

export const ACCELERATION_CONFIGS: Record<string, AccelerationConfig> = {
  Authentication: {
    dataModel: 'Authentication',
    dataset: 'Authentication',
    accelerationPeriod: '1month',
    summaryRange: '5min',
    cronSchedule: '*/5 * * * *',
    estimatedDiskGB: '2-5 GB/month per 1000 users',
    keyFields: ['user', 'src_ip', 'action', 'app', 'dest'],
    dependenciesNote: 'Requires AD, AWS IAM, or Okta log ingestion. Ensure CIM field aliases are configured for user → SubjectUserName → userIdentity.arn mapping.',
  },
  Change_Analysis: {
    dataModel: 'Change_Analysis',
    dataset: 'All_Changes',
    accelerationPeriod: '1month',
    summaryRange: '5min',
    cronSchedule: '*/5 * * * *',
    estimatedDiskGB: '3-10 GB/month per 100 instances',
    keyFields: ['user', 'command', 'object', 'object_attrs', 'dest'],
    dependenciesNote: 'Requires AWS CloudTrail, AWS Config, and Windows Security Event logs mapped to CIM. Verify eventName → command field alias.',
  },
  Network_Traffic: {
    dataModel: 'Network_Traffic',
    dataset: 'All_Traffic',
    accelerationPeriod: '1month',
    summaryRange: '5min',
    cronSchedule: '*/5 * * * *',
    estimatedDiskGB: '10-50 GB/month (high volume — tune summary range based on event rate)',
    keyFields: ['src_ip', 'dest_ip', 'dest_port', 'transport', 'bytes', 'action'],
    dependenciesNote: 'Requires VPC Flow Logs and/or proxy logs. VPC Flow Logs are extremely high volume — consider filtering before CIM mapping or use 1min summary.',
  },
  Endpoint: {
    dataModel: 'Endpoint',
    dataset: 'Processes',
    accelerationPeriod: '1month',
    summaryRange: '5min',
    cronSchedule: '*/5 * * * *',
    estimatedDiskGB: '5-20 GB/month per 500 endpoints',
    keyFields: ['process', 'process_args', 'user', 'dest', 'parent_process'],
    dependenciesNote: 'Requires CrowdStrike EDR or Sysmon data. Process command line data is critical for credential_harvest and persistence detections.',
  },
  Data_Access: {
    dataModel: 'Data_Access',
    dataset: 'All_Data_Access',
    accelerationPeriod: '1month',
    summaryRange: '5min',
    cronSchedule: '*/5 * * * *',
    estimatedDiskGB: '3-8 GB/month',
    keyFields: ['user', 'file_name', 'file_size', 'policy', 'dest'],
    dependenciesNote: 'Requires DLP (Symantec/Forcepoint) and/or S3 access logs. Map rule_name → policy, file_name → file_name, Severity → severity.',
  },
  Intrusion_Detection: {
    dataModel: 'Intrusion_Detection',
    dataset: 'IDS_Attacks',
    accelerationPeriod: '1month',
    summaryRange: '1min',
    cronSchedule: '* * * * *',
    estimatedDiskGB: '1-5 GB/month',
    keyFields: ['dest', 'signature', 'severity', 'category', 'src_ip'],
    dependenciesNote: 'Requires AWS GuardDuty findings. Map GuardDuty finding type → signature, severity → severity.',
  },
  Web: {
    dataModel: 'Web',
    dataset: 'Web',
    accelerationPeriod: '1month',
    summaryRange: '5min',
    cronSchedule: '*/5 * * * *',
    estimatedDiskGB: '5-30 GB/month (high volume — consider 1min summary for large environments)',
    keyFields: ['user', 'src_ip', 'dest_host', 'uri', 'bytes', 'http_method'],
    dependenciesNote: 'Requires proxy/web gateway logs. High cardinality — tune summary range based on unique dest_host count per day.',
  },
};

export function getAccelerationForDataModel(dataModel: string): AccelerationConfig | null {
  return ACCELERATION_CONFIGS[dataModel] || null;
}

export function generateAccelerationYAML(): string {
  const entries = Object.entries(ACCELERATION_CONFIGS).map(([name, config]) =>
    `# --- ${name} ---
${name.toLowerCase()}_acceleration:
  datamodel: "${config.dataModel}"
  dataset: "${config.dataset}"
  acceleration_period: "${config.accelerationPeriod}"
  summary_range: "${config.summaryRange}"
  cron_schedule: "${config.cronSchedule}"
  estimated_disk_gb: "${config.estimatedDiskGB}"
  key_fields: [${config.keyFields.map(f => `"${f}"`).join(', ')}]
  dependencies: "${config.dependenciesNote}"`
  ).join('\n\n');

  return `# Splunk Data Model Acceleration Configuration
# Generated by WaldoHunt 2.0
# Paste into Splunk ES Settings → Data Models → Acceleration

${entries}
`;
}
