// Asset & Identity correlation configuration for Splunk ES
// Maps detection fields to asset/identity lookups for enriched correlation

export interface AssetIdentityConfig {
  identityFields: { field: string; lookup: string; category: string; weighting: string }[];
  assetFields: { field: string; lookup: string; category: string; weighting: string }[];
  mergeStrategy: string;
}

export function generateAssetIdentityConfig(env: 'aws' | 'onprem', activity: string): AssetIdentityConfig {
  if (env === 'aws') {
    return {
      identityFields: [
        { field: 'userIdentity.arn', lookup: 'aws_iam_identities', category: 'aws_iam', weighting: 'high' },
        { field: 'sourceIPAddress', lookup: 'corp_ip_identity', category: 'network_identity', weighting: 'medium' },
        { field: 'userAgent', lookup: 'user_agent_registry', category: 'device_fingerprint', weighting: 'low' },
      ],
      assetFields: [
        { field: 'awsRegion', lookup: 'aws_region_registry', category: 'cloud_location', weighting: 'low' },
        { field: 'eventSource', lookup: 'aws_service_catalog', category: 'service_asset', weighting: 'medium' },
        { field: 'requestParameters.bucketName', lookup: 's3_bucket_catalog', category: 'storage_asset', weighting: 'medium' },
      ],
      mergeStrategy: 'Append matching identity and asset fields. Correlate eventSource with service catalog for dependency mapping.',
    };
  }

  return {
    identityFields: [
      { field: 'SubjectUserName', lookup: 'ad_identity_catalog', category: 'active_directory', weighting: 'high' },
      { field: 'SubjectDomainName', lookup: 'domain_registry', category: 'domain_identity', weighting: 'medium' },
      { field: 'IpAddress', lookup: 'dhcp_identity', category: 'network_identity', weighting: 'medium' },
    ],
    assetFields: [
      { field: 'ComputerName', lookup: 'cmdb_assets', category: 'endpoint_asset', weighting: 'high' },
      { field: 'WorkstationName', lookup: 'cmdb_assets', category: 'endpoint_asset', weighting: 'medium' },
    ],
    mergeStrategy: 'Append matching AD identity to asset records. Correlate ComputerName across all detections for lateral movement tracking.',
  };
}

// Splunk ES asset/identity correlation YAML
export function generateAssetIdentityYAML(env: 'aws' | 'onprem', activity: string): string {
  const config = generateAssetIdentityConfig(env, activity);
  const identityFields = config.identityFields.map((f) =>
    `    - field: "${f.field}"\n      lookup: "${f.lookup}"\n      category: "${f.category}"\n      weighting: "${f.weighting}"`
  ).join('\n');
  const assetFields = config.assetFields.map((f) =>
    `    - field: "${f.field}"\n      lookup: "${f.lookup}"\n      category: "${f.category}"\n      weighting: "${f.weighting}"`
  ).join('\n');

  return `# Asset & Identity Correlation Configuration
# Activity: ${activity} | Environment: ${env}
# Generated by WaldoHunt 2.0

correlation:
  merge_strategy: "${config.mergeStrategy}"

  identity_fields:
${identityFields}

  asset_fields:
${assetFields}

  # Splunk ES correlation search stanza (append to savedsearches.conf):
  # action.correlationsearch.asset_fields = ${config.assetFields.map(f => f.field).join(',')}
  # action.correlationsearch.identity_fields = ${config.identityFields.map(f => f.field).join(',')}
  # action.correlationsearch.merge_strategy = append
`;
}
