// Splunk Enterprise Security correlation search defaults
// Production-ready scheduling, throttling, and notable event field mappings

export interface CorrelationSearchConfig {
  searchName: string;
  description: string;
  search: string;
  cronSchedule: string;
  earliestTime: string;
  latestTime: string;
  alertSuppression: {
    fields: string[];
    period: string;
  };
  notableEvent: {
    severity: string;
    category: string;
    subcategory: string;
    description: string;
    drilldown: string;
    nextSteps: string;
  };
  riskScores: {
    riskObject: string;
    riskObjectField: string;
    riskScore: string;
  };
}

export function generateCorrelationConfig(
  act: string,
  title: string,
  spl: string,
  env: 'aws' | 'onprem'
): CorrelationSearchConfig {
  const defaultSeverity = getDefaultSeverity(act);
  const defaultCron = getDefaultCron(act);

  return {
    searchName: `INSIDER - ${env === 'aws' ? 'AWS' : 'OnPrem'} - ${title}`,
    description: `CERT/CC Insider Threat detection for ${title}. Environment: ${env === 'aws' ? 'AWS Cloud' : 'On-Prem / Hybrid'}. Generated by WaldoHunt 2.0.`,
    search: spl,
    cronSchedule: defaultCron,
    earliestTime: '-24h@h',
    latestTime: 'now',
    alertSuppression: {
      fields: ['userIdentity.arn', 'eventName'],
      period: '1h',
    },
    notableEvent: {
      severity: defaultSeverity,
      category: 'Insider Threat',
      subcategory: title,
      description: `Insider Threat: ${title} detected in ${env === 'aws' ? 'AWS' : 'on-prem'} environment\n\nDetection: $result.detection_summary$\nUser: $result.user$\nCount: $result.count$\nRisk: $result.risk$\n\nSee MITRE ATT&CK mapping for relevant TTPs.`,
      drilldown: 'search $search$',
      nextSteps: `1. Verify if the activity is authorized (check change management)\n2. Review user\'s recent activity for additional indicators\n3. Check for correlated alerts (privilege escalation, data staging)\n4. Contact user\'s manager if activity is suspicious\n5. Escalate to SOC Tier 2 if risk = CRITICAL`,
    },
    riskScores: {
      riskObject: 'user',
      riskObjectField: 'userIdentity.arn',
      riskScore: getDefaultRiskScore(defaultSeverity),
    },
  };
}

function getDefaultSeverity(act: string): string {
  const critical: string[] = ['priv_escalation', 'credential_harvest', 'log_tamper'];
  const high: string[] = ['delete_data', 'resource_destroy', 'config_tamper', 'backup_destroy', 'access_revoke',
    'secrets_access', 'usb_exfil', 'persistence'];
  const medium: string[] = ['s3_exfil', 'repo_clone', 'data_stage', 'cross_account',
    'resource_abuse', 'policy_bypass', 'account_create', 'financial_manip',
    'recon', 'sensitive_access', 'lateral_move', 'c2_comms'];

  if (critical.includes(act)) return 'critical';
  if (high.includes(act)) return 'high';
  if (medium.includes(act)) return 'medium';
  return 'medium';
}

function getDefaultRiskScore(severity: string): string {
  switch (severity) {
    case 'critical': return '90';
    case 'high': return '70';
    case 'medium': return '50';
    case 'low': return '30';
    default: return '50';
  }
}

function getDefaultCron(act: string): string {
  // Higher frequency for time-sensitive detections
  const frequent: string[] = ['priv_escalation', 'log_tamper', 'credential_harvest'];
  const hourly: string[] = ['delete_data', 'resource_destroy', 'config_tamper',
    'backup_destroy', 'access_revoke', 'secrets_access', 'persistence', 'c2_comms', 'usb_exfil'];
  const daily: string[] = ['s3_exfil', 'repo_clone', 'data_stage', 'cross_account',
    'resource_abuse', 'policy_bypass', 'account_create', 'financial_manip',
    'recon', 'sensitive_access', 'lateral_move'];

  if (frequent.includes(act)) return '*/15 * * * *';
  if (hourly.includes(act)) return '5 * * * *';
  if (daily.includes(act)) return '45 */6 * * *';
  return '5 * * * *';
}

// Splunk ES correlation search YAML template (for detection-as-code)
export function generateCorrelationYAML(config: CorrelationSearchConfig): string {
  return `# WaldoHunt 2.0 — Detection as Code
# Generated: ${new Date().toISOString()}
# Framework: CERT/CC Insider Threat Framework
# Environment: Splunk Enterprise Security

name: "${config.searchName}"
description: "${config.description}"
search: |
  ${config.search.replace(/\n/g, '\n  ')}

schedule:
  cron: "${config.cronSchedule}"
  earliest_time: "${config.earliestTime}"
  latest_time: "${config.latestTime}"

alert:
  severity: "${config.notableEvent.severity}"
  category: "${config.notableEvent.category}"
  subcategory: "${config.notableEvent.subcategory}"
  description: "${config.notableEvent.description}"
  drilldown: "${config.notableEvent.drilldown}"
  next_steps: "${config.notableEvent.nextSteps}"

suppression:
  fields: [${config.alertSuppression.fields.map(f => `"${f}"`).join(', ')}]
  period: "${config.alertSuppression.period}"

risk:
  object: "${config.riskScores.riskObject}"
  object_field: "${config.riskScores.riskObjectField}"
  score: "${config.riskScores.riskScore}"

tags:
  - waldo-hunt
  - insider-threat
  - cert-cc
  - mitre-attack
`;
}
